app = "alluracare"
primary_region = "lhr"

[build]
  builder = "heroku/builder:22"

[env]
  PORT = "8000"
  PYTHONUNBUFFERED = "1"
  DJANGO_SETTINGS_MODULE = "allura_project.settings"
  DEBUG = "False"
  # You'll need to set these in Fly.io secrets:
  # SECRET_KEY
  # GMAIL_USER_EMAIL
  # GMAIL_USER_PASSWORD

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[processes]
  app = "gunicorn allura_project.wsgi:application"

[[statics]]
  guest_path = "/app/static"
  url_prefix = "/static/"
