app = "alluracare"
primary_region = "lhr"  # London region, change if needed

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/app/static"
  url_prefix = "/static/"

[deploy]
  release_command = "python manage.py migrate"
