app = "alluracare"
primary_region = "lhr"

[build]
  builder = "heroku/buildpacks:20"

[env]
  PORT = "8000"
  PYTHONUNBUFFERED = "1"
  DJANGO_SETTINGS_MODULE = "allura_project.settings"  # Change this to your Django settings module name

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[processes]
  app = "gunicorn allura_project.wsgi:application"  # Change allura_project to your project name

[[statics]]
  guest_path = "/app/static"
  url_prefix = "/static/"
